### ISSUE TITLE
Report upload fails

### ISSUE THREAD

**Issue by wheelq** [archerysec/archerysec-cli#1]
I have exported report in JSON format, using archerysec GUI.
Then I wanted to re-import same JSON file using archerysec-cli. But it looks like it fails:

` archerysec-cli -s http://xxx.xxx.xxx.xxx:9000 -u admin -p xxxxxxxx  --upload --file=report_arachni.json --TARGET="https://xxxxxxxxx/" --file_type=JSON --scanner=arachni --project_id="81111111-1111-1111-1116-111111111111"1

And here is the result:
![image](https://user-images.githubusercontent.com/1497172/55938909-5e338400-5c34-11e9-91ef-bca50fcabb3d.png)

**Comment by wheelq** [comment]
why is it closed?

**Comment by anandtiwarics** [comment]
--scanner=arachni  supports only XML file. please use xml file.
Duplicate of #2
