### ISSUE TITLE
Error 401 "detail": "Authentication credentials were not provided."

### ISSUE THREAD

**Issue by Bank4500** [archerysec/archerysec-cli#10]
http://localhost:8000/api/webscan/?format=api

Please help me. I have a problem with the web api invalid. Where should I go to fix it?

![Error401](https://user-images.githubusercontent.com/36659705/128666923-658e7215-e965-4a0e-8963-b8fc4bf53240.png)

**Comment by anandtiwarics** [comment]
please visit in our API document https://developers.archerysec.com/
