### ISSUE TITLE
Error while publishing nodejsscan and trivy reports

### ISSUE THREAD

**Issue by sourabhgupta385** [archerysec/archerysec-cli#13]
Reports are generated in Jenkins using:

```
sh "njsscan src --json -o 'nodejs-scanner-report.json'"
sh script: 'TRIVY_NEW_JSON_SCHEMA=true trivy --cache-dir /tmp/trivy image --format json -o trivy-report.json --input hello_world_${BUILD_NUMBER}.tar'
```
Reports are published using:
```
sh "archerysec-cli -s ${properties.ARCHERYSEC_HOST_URL} -u ${ARCHERYSEC_USERNAME} -p ${ARCHERYSEC_PASSWORD} --upload --file_type=JSON --file=trivy-report.json --TARGET=DVNA_TRIVY --scanner=trivy --project_id=655016af-2e40-47da-b4e2-da91db041fda"
```

**Output**

  <title>TypeError
          at /api/uploadscan/</title>

```
sh "archerysec-cli -s ${properties.ARCHERYSEC_HOST_URL} -u ${ARCHERYSEC_USERNAME} -p ${ARCHERYSEC_PASSWORD} --upload --file_type=JSON --file=nodejs-scanner-report.json --TARGET=DVNA_NODEJSSCAN --scanner=nodejsscan --project_id=655016af-2e40-47da-b4e2-da91db041fda"
```

**Output**

  <title>KeyError
          at /api/uploadscan/</title>

On the console, everything is showing as none for trivy and nodejsscan as below:

![image](https://user-images.githubusercontent.com/22052614/129030379-cbc87415-4589-487e-818d-d64ce7a72110.png)

Did anyone tried publishing trivy and nodejsscan reports using CLI?

**Comment by sourabhgupta385** [comment]
I got trivy working by changing the command to:

```
sh script: 'trivy --cache-dir /tmp/trivy image --format json -o trivy-report.json --input hello_world_${BUILD_NUMBER}.tar'

```

Basically, trivy has changed schema of json output in new version which is not compatible here yet. Previous version is working absolutely fine.

![image](https://user-images.githubusercontent.com/22052614/129033494-673b977f-1aed-4e23-9fa7-196cd65e1a84.png)

**Comment by ghost** [comment]
@sourabhgupta385 did u resolved the nodejsscan issue? Even I'm getting the same issue

**Comment by sourabhgupta385** [comment]
Hi @ihangnalli-cci ,

I did not investigated much on nodejsscan error. I then chose to prefer HTML report publishing in Jenkins for NodeJs scan.

**Comment by ghost** [comment]
Ok. Thanks for the reply @sourabhgupta385

**Comment by ghost** [comment]
@sourabhgupta385 I found what was the issues with this. It was not getting uploaded because the file formatting of the report  generated of nodejsscan json file is different from the previous version. 

@anandtiwarics Can you look into this. I have attached a sample file for your reference.
[sample.zip](https://github.com/archerysec/archerysec-cli/files/10341452/sample.zip)

**Comment by anandtiwarics** [comment]
we are currently supported file list https://github.com/archerysec/report-sample/tree/main/Trivy
