### ISSUE TITLE
How to integrate Nessus scan with archerysec-cli

### ISSUE THREAD

**Issue by piyushibhargava27** [archerysec/archerysec-cli#6]
What is the cli command to upload Nessus scan reports?

**Comment by anandtiwarics** [comment]
`archerysec-cli -s http://127.0.0.1:8000 -u admin -p admin@123 --upload --file_type=XML --file=/Users/xxxxxx/work/xxxx/sample/report.nessus --TARGET=test --scanner=nessus --project_id=9d623292-83ce-452f-a163-446056b0273c`
