### ISSUE TITLE
null problem

### ISSUE THREAD

**Issue by Bank4500** [archerysec/archerysec-cli#9]
I'm having trouble with archerysec right now.

We can create project using CLI commands:

$ archerysec-cli -s http://192.168.222.131:8000 -u Bank -p 123456 --createproject \
 --project_name=test_project --project_disc="test project" --project_start=2021-07-30 \
  --project_end=2021-07-30 --project_owner=Bank

Output:

{"message": "Project Created", "project_id": "4b4303bc-2cd6-4212-8801-231e8b10be6d"}
We can launch scan(s) using CLI:

$ archerysec-cli -s http://192.168.222.131:8000 -u Bank -p 123456 \
 --zapscan --target_url=http://demo.testfire.net \
  --project_id=4b4303bc-2cd6-4212-8801-231e8b10be6d

Output:

null

I'm not sure if I forgot to install something or forgot to add something.
![hphQaq40](https://user-images.githubusercontent.com/36659705/127652701-0d9b2b8a-775e-4e8e-a1bd-d97098011e2d.png)
![ImcE93gz](https://user-images.githubusercontent.com/36659705/127652709-909f6ac7-4286-4a76-b1d5-5ac684af906c.png)

**Comment by Bank4500** [comment]
How should I fix scan id null?

**Comment by slackerwx** [comment]
I'm having the same problem

**Comment by anandtiwarics** [comment]
hi, please use a released version of [archerysec](https://github.com/archerysec/archerysec/releases/tag/v2.0.1) we are working on major changes on the master branch.
